<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LEPTA.Shared\LEPTA.Shared.csproj" />
    <ProjectReference Include="..\LEPTA.Infrastracture\LEPTA.Infrastracture.csproj" />
    <ProjectReference Include="..\LEPTA.vLLM\LEPTA.vLLM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="NLog" Version="6.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
